---
# Install Python 3 Packages

- name: Update pip2
  pip: name="pip" state=latest executable=pip3
  become: true

- name: Install python3 packages with pip3
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: present
    extra_args: "--no-cache-dir"
    executable: pip3
  with_items: "{{ pip3_packages | default([]) }}"
  become: true